### ISSUE TITLE
Knowledge transfer

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backlog#87]
# Architectural design decisions for the new version

## GUI Forms
Classically forms were rendered directly in PHP. With the goal of moving towards an API supported by a client side (js) frontend we've made some changes to how forms are defined and rendered. Forms are defined as SurveyJS surveys. The `FormRepository` class offers an easy way to load the forms.

## Grids
Grids used to be rendered directly in PHP with a sauce of JS for interactivity. Instead we've moved to ag-grid (https://ag-grid.com/) which is fully interactive. The data is pulled from the API therefore keeping the backend code lightweight.

## API Security
Making API calls requires authentication. Since we want to be able to make API calls from the browser we need some way to authenticate the browser; however the browser has limited options for securely storing credentials.
To prevent the need for our API to support cookies, we decided to proxy API request through our backend.
The backend uses session HTTP-only cookies, the most used and therefor most secure mechanism of having session identifiers in your frontend. When an API call is made it is proxied through the backend which after authenticating the user and authorizing the request creates a JWT and passes it to the API.

# Production environment description

  - [x] Database: DigitalOcean
  - [x] Kubernetes via DOKS
  - [x] Automatically deployment happens on push to the `k8s-prod` branch
  - [x] Cert Manager refreshes SSL certificates using the DigitalOcean DNS API (https://cert-manager.io/)
  - [x] Secrets are stored in this repository encrypted using Sealed secrets controller  (https://github.com/bitnami-labs/sealed-secrets)

# Authentication

Passwords are stored as salted hashes using the standard `hash_password` and `hash_verify` family of PHP functions

## Frontend / backend
A standard cookie based session is used. Login happens through a classic HTML form.

## API
- In the development branch the API and backend / frontend are split
- The API uses JWTs for authentication
- The backend proxies requests for the frontend to the API; this is because the frontend cannot securely store a secret for authenticating with the API
- The backend creates signed JWTs for authentication with the API; these are only valid for a very short time

# Translation
- Using weblate which runs on Kubernetes
- Translations are automatically synchronized with https://github.com/herams-who/herams-i18n
- Weblate pushes translations and github actions push updated base files to the repo

# Assets / secrets that need transfer

- [x] Digital ocean team. @matof-who is now owner
- [x] #89
- [x] #90
- [x] Database: hosted database in DO. Credentials can be found / recreated in the DO portal (https://cloud.digitalocean.com)

# Todo
- [x] Clean-up repos, unused repos and code
- [x] Clean-up backlog, check if there's issues not in the project
- [x] Run documentation
- [x] #88
- [x] Finish branch strategy

**Comment by matof-who** [comment]
@SamMousa Working on the weblate documentation ... I realise I do not have admin access to the HeRAMS project
Could you please grant me access ? I've already registered to Weblate as matof@who.int

**Comment by SamMousa** [comment]
> @SamMousa Working on the weblate documentation ... I realise I do not have admin access to the HeRAMS project Could you please grant me access ? I've already registered to Weblate as [matof@who.int](mailto:matof@who.int)

Hmm, forgot to let you know, but you should have admin access now.

**Comment by SamMousa** [comment]
Document how we use secrets: https://sealed-secrets.netlify.app/

**Comment by matof-who** [comment]
Hi @SamMousa 
I've cleaned all issues in the herams-backend repository, all open issues have been tagged and moved to the herams-backlog
However, I see some open issues in other repositories. Are this issues still relevant ? 

If not, I will close them to have all clean :)


![Image](https://user-images.githubusercontent.com/70581697/223694418-44f27fd5-aa9d-4513-8209-25c3bccd0bf6.png)


![Image](https://user-images.githubusercontent.com/70581697/223694445-c3e510d9-6450-4863-bcec-1887e17c2ae1.png)


![Image](https://user-images.githubusercontent.com/70581697/223694498-555a8bf4-8a5c-402f-abb9-144c4f26339a.png)

**Comment by SamMousa** [comment]
The archived repository is not relevant, nothing is relevant if it is archived.
The dashboard-cards are a proof of concept / basic implementation of the cards for new dashboards in v2. So they should probably remain open.

Herams-support is owned by the business not the dev team.
